// Mint-Agent project site · bilingual copy
// Condensed project-website copy distilled from the official release narrative.
window.SITE_COPY = {
  zh: {
    _meta_title: "Mint-Agent · 金融原生 Agentic Foundation Model",
    _lang_btn: "EN · English",

    nav_results: "结果",
    nav_stack: "技术框架",
    nav_cases: "轨迹案例",
    nav_contact: "联系",
    nav_demo: "试用 Demo",

    hero_eyebrow: "MINT AGENT · 金融基座模型技术报告",
    hero_title: "金融原生 Agentic Foundation Model<br /><span class=\"accent\">Mint-Agent 正式发布</span>",
    hero_lede: "9B 的 Mint-Cu 与 27B 的 Mint-Ag，把证据、计算与长程执行统一起来——面向可追溯、可复算、能够执行到底的金融研究。",
    model_cu: "9B · 紧凑执行",
    model_ag: "27B · 能力上限",
    hero_cta1: "先看结果",
    hero_cta2: "了解技术框架",
    stat_t3: "FinSearchComp T3<br />并列第一",
    stat_family: "模型家族",

    premise_p1: "一个 Agentic Model 可以给出正确数字，却引用了错误财年；也可以写出完整分析，却混用了单位。在投研、风控和审计中，<strong>这样的答案不能用。</strong>",
    fail1_tag: "错误案例 · 时点错配",
    fail1_body: "数字正确，却引用了错误财年——结论看起来合理，实际上不成立。",
    fail2_tag: "错误案例 · 单位混用",
    fail2_body: "分析完整，计算却混用了“元”和“万元”——任何下游决策都会被放大误导。",
    premise_p2: "面向金融的标准必须更高。在 Mint-Agent 这里，可靠性不是抽象评分，而是能否把错误定位到来源、期间、抽取或计算中的<strong>具体一步</strong>。",
    std1: "信息来自正确来源",
    std2: "时间点严格匹配",
    std3: "计算能够复现",
    std4: "结论回到证据",
    premise_quote: "每一个金融结论，都必须留下一条可恢复、可检查的路径。",

    results_kicker: "Results · 先看结果",
    results_title: "把“可靠”与“能执行”放进同一张答卷",
    results_sub: "可靠性、执行力与紧凑性，来自同一个模型家族，而不是三个互相妥协的版本。",
    card1_label: "可靠性 · Reliability",
    card1_note: "分别领先 GPT-5.6-Sol <span class=\"delta\">3.66</span> 个百分点、Claude Opus 4.8 <span class=\"delta\">3.00</span> 个百分点；FinanceBench 得分 <span class=\"delta\">91.33%</span>。",
    card2_label: "执行力 · Execution",
    card2_note: "FinSearchComp T3 并列第一；FinanceAgentBench v1.1 <span class=\"delta\">76.00%</span>、v2 <span class=\"delta\">60.49%</span>，FinSearchComp T2 <span class=\"delta\">89.04%</span>。",
    card3_label: "紧凑性 · Compactness",
    card3_note: "9B 的 Mint-Cu 分别超过 Agents-A1-35B 与 Nex-N2-mini <span class=\"delta\">22.83</span> 和 <span class=\"delta\">12.78</span> 个百分点。",
    fig1_no: "图 1",
    fig1_cap: "六项核心金融评测：上排考察有界推理与可靠性，下排考察开放环境中的搜索与长程执行；FinanceAgentBench v2 为三次运行均值。",
    results_close: "重点不在单项榜首，而在两类能力没有彼此牺牲：27B 的 Mint-Ag 提供能力上限，9B 的 Mint-Cu 证明小体量也能承担复杂的金融搜索与执行。",



    stack_kicker: "Tech Stack · 技术框架",
    stack_title: "三位一体：Data、Harness、Algorithm",
    stack_sub: "三部分共享同一套金融正确性标准：来源、报告期、指标、数值、单位和计算，必须能够被重新检查。",
    fig2_no: "图 2",
    fig2_cap: "Data 定义什么算对，Harness 保存模型如何执行，Algorithm 把推理与执行训练进同一策略。",

    data_title: "Data：先把“什么算对”定义清楚",
    data_sub: "只有证据支持、计算可重放、答案唯一的样本，才进入训练。",
    data_pt1: "<strong>五类原子任务</strong>：知识、提取、计算、分析、验证。",
    data_pt2: "材料来自 EDGAR、XBRL、交易所记录与 FRED；每个事实绑定<strong>实体、期间、指标、数值、单位与原始位置</strong>。",
    data_pt3: "证据支持、计算可重放、答案唯一——三关全过，样本才进入训练。",
    fig3_no: "图 3",
    fig3_cap: "原子任务构造：从权威来源采样，抽取带定位的事实，按五类能力生成任务，经验证门控后入库。",
    data_p2: "长程任务只暴露研究目标：预先构建的<strong>隐藏证据图</strong>固定了所需事实与运算路径，模型必须在开放环境中自己恢复这条路径，而不能从题面获得答案。",
    fig4_no: "图 4",
    fig4_cap: "长程任务构造与验证：来源包与隐藏证据图不向模型暴露，只用于核验轨迹可重放、答案唯一、证据可定位。",

    harness_title: "Harness：证据不能随着上下文一起消失",
    harness_sub: "已经确认的证据，不会被后续对话覆盖。",
    harness_pt1: "模型决定行动；Harness 校验工具、预算与输出格式。",
    harness_pt2: "有效结果写入 <strong>Evidence Ledger</strong>，与失败的检索路径严格分开。",
    harness_pt3: "证据账本、工作记忆与完整轨迹保存在<strong>模型上下文之外</strong>，不随压缩丢失。",
    fig5_no: "图 5",
    fig5_cap: "状态化执行循环：证据账本、工作记忆与完整轨迹持续更新；隐藏答案只留在隔离的评估侧。",
    harness_p3: "即使任务经历网页失效、搜索转向或多轮压缩，已确认的证据也不会被覆盖；碰巧正确但证据无法支持的答案，<strong>不算完成任务</strong>。",

    algo_title: "Algorithm：双核训练，能力合一",
    algo_sub: "分别训练两位专家，再收敛到同一模型。",
    algo_pt1: "从同一基础模型出发，分别训练<strong>金融推理专家</strong>与 <strong>Agentic 执行专家</strong>。",
    algo_pt2: "分工避免两类能力在训练早期相互牵制，再经 <strong>TIES 与 MOPD</strong> 收敛进同一策略。",
    algo_pt3: "MOPD 把合并损失追回来——一个模型，同时保留两种能力。",
    fig6_no: "图 6",
    fig6_cap: "双专家训练与统一流程：上路负责有界金融推理，下路负责长程执行，最终汇入 Mint-Cu 与 Mint-Ag。",

    cases_kicker: "Trajectories · 轨迹",
    cases_title: "结果之外，真正值得看的是轨迹",
    cases_sub: "轨迹记录的不只是最终答案，还有失败检索、时间冲突、证据锁定与计算复核如何被处理。",
    case1_title: "AMD 收入指引：长程恢复",
    case1_meta: "13 步 · 23 次工具调用",
    case1_p1: "模型否决错误的 accession，扩大 SEC 检索，定位四个季度的 EX-99.1，并在输出前重新打开 Q3 来源复核。",
    case1_p2: "失败被明确记录，并触发可追踪的路径修正。系统允许可见、可纠正的失败，<strong>不接受无法解释的“正确答案”</strong>。",
    fig7_cap: "图 7｜AMD 收入指引轨迹。点击图片可放大查看完整轨迹。",
    case2_title: "TSMC Q1 2025 收入预测：37 步长程执行",
    case2_meta: "37 步 · 72 次工具调用",
    case2_p1: "模型否决年度数据绕行，锁定台积电官方月度收入表，审计 6-K 与错误季度页，在统一汇率假设下重建三年历史区间，最终以 0.96% 的偏差复算出指引中点差距。",
    case2_p2: "<strong>37 步、72 次工具调用，不丢失一条证据</strong>：绕行被纠正、失败被记录、缓存被复用，最终结论连同汇率假设与三年基线一起交付，全程可复算。",
    fig8_cap: "图 8｜TSMC Q1 2025 收入预测轨迹。点击图片可放大查看完整轨迹。",
    cases_close: "审计性不是报告末尾补几条引用，而是模型完成任务所依赖的状态；这些轨迹同时为数据筛选、关键步骤修复和强化学习提供可定位的训练信号。",

    concl_kicker: "Conclusion · 可审计是金融底线",
    concl_title: "金融不会容忍“差不多正确”",
    concl_p1: "数据先定义证据，Harness 保留执行状态，算法把正确行为写进策略——<strong>可审计性不是推理后的说明层，而是三者共同依赖的底座。</strong>下一阶段的竞争，不是谁更像分析师，而是谁能把任务完成，并为每一个结论留下可检查的依据。",


    contact_kicker: "Contact Us · 联系我们",
    contact_title: "想要使用 Mint-Agent？",
    contact_sub: "输入邀请码即刻开始，或发送邮件向我们申请访问资格。",
    invite_tag: "Invitation Code",
    invite_title: "已有邀请码",
    invite_desc: "输入邀请码，系统将为你分配专属账号，用于登录 Mint-Agent 研究工作台。",
    invite_placeholder: "请输入邀请码",
    invite_btn: "兑换账号",
    invite_empty: "请先输入邀请码。",
    invite_checking: "正在验证邀请码…",
    invite_invalid: "邀请码无效或已被使用。",
    invite_ratelimited: "尝试次数过多，请稍后再试。",
    invite_network: "网络异常，请稍后再试。",
    invite_success_note: "账号已创建。以下凭据仅显示这一次，请立即保存：",
    invite_user_label: "用户名",
    invite_pass_label: "密码",
    invite_copy: "复制",
    invite_copied: "已复制",
    invite_go_app: "前往 Mint-Agent 研究工作台 →",
    invite_have_account: "已有账号？直接登录 →",
    mail_tag: "Email",
    mail_title: "申请访问",
    mail_desc: "暂无邀请码？发送邮件简要说明你的机构与使用场景，我们会尽快回复。",

    foot_end: "Minds in Finance",
    lb_hint: "点击任意处关闭",
  },

  en: {
    _meta_title: "Mint-Agent · Finance-Native Agentic Foundation Models",
    _lang_btn: "中 · Chinese",

    nav_results: "Results",
    nav_stack: "Tech Stack",
    nav_cases: "Trajectories",
    nav_contact: "Contact",
    nav_demo: "Try the Demo",

    hero_eyebrow: "MINT AGENT · Financial Foundation Model Report",
    hero_title: "Introducing Finance-Native Agentic Foundation Models, <br /><span class=\"accent\">Mint-Agent</span>",
    hero_lede: "Mint-Cu (9B) and Mint-Ag (27B) unify evidence, computation, and long-horizon execution — built for financial research that is traceable, recomputable, and executed to completion.",
    model_cu: "9B · Compact execution",
    model_ag: "27B · Full capability",
    hero_cta1: "See the results",
    hero_cta2: "Explore the stack",
    stat_t3: "FinSearchComp T3<br />Tied #1",
    stat_family: "Model family",

    premise_p1: "An agentic model can produce the right number while citing the wrong fiscal year — or a complete analysis that silently mixes units. In equity research, risk, and audit, <strong>such an answer cannot be used.</strong>",
    fail1_tag: "Failure mode · Wrong period",
    fail1_body: "The number is right, but it cites the wrong fiscal year — the conclusion looks plausible yet does not hold.",
    fail2_tag: "Failure mode · Unit mixing",
    fail2_body: "The analysis reads complete, but the calculation mixes units — and every downstream decision amplifies the error.",
    premise_p2: "Finance demands a higher bar. For Mint-Agent, reliability is not an abstract score — it is whether an error can be localized to <strong>one specific step</strong> in sourcing, period selection, extraction, or computation.",
    std1: "Right source",
    std2: "Matching period",
    std3: "Reproducible computation",
    std4: "Evidence-backed conclusion",
    premise_quote: "Every financial conclusion must leave behind a path that can be recovered and checked.",

    results_kicker: "Results first",
    results_title: "Reliability and execution, on the same scorecard",
    results_sub: "Reliability, execution, and compactness — from one model family, not three compromised variants.",
    card1_label: "Reliability",
    card1_note: "Ahead of GPT-5.6-Sol by <span class=\"delta\">3.66</span> points and Claude Opus 4.8 by <span class=\"delta\">3.00</span> points; FinanceBench <span class=\"delta\">91.33%</span>.",
    card2_label: "Execution",
    card2_note: "Tied #1 on FinSearchComp T3; FinanceAgentBench v1.1 <span class=\"delta\">76.00%</span>, v2 <span class=\"delta\">60.49%</span>, FinSearchComp T2 <span class=\"delta\">89.04%</span>.",
    card3_label: "Compactness",
    card3_note: "The 9B Mint-Cu beats Agents-A1-35B by <span class=\"delta\">22.83</span> points and Nex-N2-mini by <span class=\"delta\">12.78</span> points.",
    fig1_no: "Fig. 1",
    fig1_cap: "Six core financial benchmarks: the top row measures bounded reasoning and reliability; the bottom row measures open-environment search and long-horizon execution. FinanceAgentBench v2 is averaged over three runs.",
    results_close: "The point is not any single first place, but that neither capability was sacrificed: the 27B Mint-Ag sets the ceiling, and the 9B Mint-Cu proves a compact model can still execute complex financial research.",



    stack_kicker: "Tech stack",
    stack_title: "A trinity: Data, Harness, Algorithm",
    stack_sub: "All three share one standard of financial correctness: sources, periods, metrics, values, units, and calculations must be re-checkable.",
    fig2_no: "Fig. 2",
    fig2_cap: "Data defines what counts as correct, Harness preserves how the model executes, and Algorithm trains reasoning and execution into one policy.",

    data_title: "Data: define “what counts as correct” first",
    data_sub: "Only samples that are evidence-backed, replayable, and uniquely answerable enter training.",
    data_pt1: "<strong>Five atomic task types</strong>: knowledge, extraction, calculation, analysis, verification.",
    data_pt2: "Materials from EDGAR, XBRL, exchange records, and FRED; every fact is bound to an <strong>entity, period, metric, value, unit, and source locator</strong>.",
    data_pt3: "Three gates — evidence holds, computation replays, answer is unique — before a sample enters training.",
    fig3_no: "Fig. 3",
    fig3_cap: "Atomic task construction: sample from authoritative sources, extract located facts, generate tasks across five capabilities, gate by verification.",
    data_p2: "Long-horizon tasks expose only the research objective: a pre-built <strong>hidden evidence graph</strong> pins the required facts and computational paths, and the model must recover the path itself in an open environment — the prompt never leaks the answer.",
    fig4_no: "Fig. 4",
    fig4_cap: "Long-horizon task construction and verification: the source pack and hidden evidence graph are never exposed to the model — they only verify that trajectories replay, answers are unique, and evidence is locatable.",

    harness_title: "Harness: evidence must not vanish with the context",
    harness_sub: "Confirmed evidence is never overwritten by later conversation.",
    harness_pt1: "The model decides actions; the Harness validates tools, budgets, and output formats.",
    harness_pt2: "Valid results go into the <strong>Evidence Ledger</strong>, kept strictly separate from failed retrieval paths.",
    harness_pt3: "The ledger, working memory, and full trajectory live <strong>outside the model context</strong> — never lost to compression.",
    fig5_no: "Fig. 5",
    fig5_cap: "The stateful execution loop: evidence ledger, working memory, and full trajectory update continuously; hidden answers stay on the isolated evaluator side.",
    harness_p3: "Even through dead links, search pivots, or repeated compression, confirmed evidence survives; an answer that happens to be right but lacks supporting evidence <strong>does not count as finishing the task</strong>.",

    algo_title: "Algorithm: dual-expert training, unified capability",
    algo_sub: "Train two experts separately, then converge them into one model.",
    algo_pt1: "From one base model, train a <strong>financial-reasoning expert</strong> and an <strong>agentic-execution expert</strong> separately.",
    algo_pt2: "The split keeps the two capabilities from constraining each other early on; <strong>TIES and MOPD</strong> then converge them into a single policy.",
    algo_pt3: "MOPD recovers the merging loss — one model, both capabilities retained.",
    fig6_no: "Fig. 6",
    fig6_cap: "Dual-expert training and unification: the upper path handles bounded financial reasoning, the lower path long-horizon execution, merging into Mint-Cu and Mint-Ag.",

    cases_kicker: "Trajectories",
    cases_title: "Beyond the scores, look at the trajectories",
    cases_sub: "A trajectory records more than the final answer: how failed retrievals, temporal conflicts, evidence locking, and computation re-checks are handled.",
    case1_title: "AMD revenue guidance: long-horizon recovery",
    case1_meta: "13 steps · 23 tool calls",
    case1_p1: "The model rejects a wrong accession number, broadens the SEC search, locates the EX-99.1 exhibits for all four quarters, and re-opens the Q3 source to verify before answering.",
    case1_p2: "Failures are explicitly recorded and trigger traceable corrections. The system tolerates visible, correctable failure — <strong>it does not accept an unexplainable “right answer.”</strong>",
    fig7_cap: "Fig. 7 | AMD revenue guidance trajectory. Click to enlarge.",
    case2_title: "TSMC Q1 2025 revenue: a 37-step projection",
    case2_meta: "37 steps · 72 tool calls",
    case2_p1: "The model rejects an annual-data detour, locks TSMC's official monthly revenue tables, audits 6-K filings and a wrong-quarter page, rebuilds the three-year window under a unified FX assumption, and reproduces the guidance-midpoint gap within 0.96%.",
    case2_p2: "<strong>37 steps, 72 tool calls, and not one piece of evidence lost</strong>: detours corrected, failures recorded, caches reused — the final answer ships with its FX assumption and three-year baseline, fully recomputable.",
    fig8_cap: "Fig. 8 | TSMC Q1 2025 revenue projection trajectory. Click to enlarge.",
    cases_close: "Auditability is not citations appended to a report — it is the state the model depends on to finish the task. These trajectories also provide locatable training signals for data filtering, critical-step repair, and reinforcement learning.",

    concl_kicker: "Conclusion · Auditability is the baseline",
    concl_title: "Finance does not tolerate “almost right”",
    concl_p1: "Data defines the evidence, the Harness preserves execution state, and the algorithm writes correct behavior into the policy — <strong>auditability is not an explanatory layer after reasoning; it is the substrate all three depend on.</strong> The next stage of competition is not who sounds most like an analyst, but who can finish the task and leave a checkable basis for every conclusion.",


    contact_kicker: "Contact us",
    contact_title: "Want to use Mint-Agent?",
    contact_sub: "Enter an invitation code to get started, or email us to request access.",
    invite_tag: "Invitation Code",
    invite_title: "Have an invitation code?",
    invite_desc:
      "Enter your code and the system will issue a dedicated account for the Mint-Agent research workspace.",
    invite_placeholder: "Enter invitation code",
    invite_btn: "Redeem",
    invite_empty: "Please enter an invitation code first.",
    invite_checking: "Verifying invitation code…",
    invite_invalid: "Invalid or already-used invitation code.",
    invite_ratelimited: "Too many attempts. Please try again later.",
    invite_network: "Network error. Please try again.",
    invite_success_note: "Account created. These credentials are shown only once — save them now:",
    invite_user_label: "Username",
    invite_pass_label: "Password",
    invite_copy: "Copy",
    invite_copied: "Copied",
    invite_go_app: "Open the Mint-Agent workspace →",
    invite_have_account: "Already have an account? Sign in →",
    mail_tag: "Email",
    mail_title: "Request access",
    mail_desc: "No code yet? Send us a short note about your organization and use case — we will get back to you soon.",

    foot_end: "Minds in Finance",
    lb_hint: "Click anywhere to close",
  },
};
